openapi: 3.0.0
info:
  title: "<script>alert('XSS')</script>"
  description: "<img src=x onerror=alert(1)>"
  version: "1.0.0"

paths:
  /test:
    get:
      summary: "Test"
      responses:
        '200':
          description: "OK"
